name: Deploy multifib on EBS AWS

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - dockerfile: ./Dockerfile
            context: client
            image: rafalbalinski/dockerrepo:fib-client
          - dockerfile: ./Dockerfile
            context: server
            image: rafalbalinski/dockerrepo:fib-server
          - dockerfile: ./Dockerfile
            context: worker
            image: rafalbalinski/dockerrepo:fib-worker
          - dockerfile: ./Dockerfile
            context: nginx
            image: rafalbalinski/dockerrepo:fib-router

    steps:

      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Buildx set-up
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: "{{defaultContext}}:${{ matrix.context }}"
          file: ${{ matrix.dockerfile }}
          push: true
          tags: ${{ matrix.image }}

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:

      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Generate deployment package
        run: zip deploy.zip ./docker-compose.yml

      - name: Deploy to EBS
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: mbmultifib
          environment_name: Mbmultifib-env-1
          version_label: zzz
          region: eu-north-1
          deployment_package: deploy.zip